---
pipelines:
#################################################
# Init States - First Level
#################################################


  - type: terraform
    path: '@kateops'
    id: kateops
    stateName: kateops

#################################################
# Second Level
#################################################

  - type: terraform
    path: '@kateops/@cluster'
    stateName: kateops/cluster
    id: cluster
    needs:
      - id: kateops
        stage: deploy
        targetStage: build


  - type: terraform
    path: '@kateops/@cluster-setup'
    id: cluster-setup
    stateName: kateops/cluster-setup
    needs:
      - id: cluster
        stage: deploy
        targetStage: build

#################################################
# Third Level
#################################################

  - type: terraform
    path: '@kateops/@monitoring'
    stateName: kateops/monitoring
    id: monitoring
    needs:
      - id: cluster-setup
        stage: deploy
        targetStage: build

  - type: terraform
    path: '@kateops/@monitoring-setup'
    id: monitoring-setup
    stateName: kateops/monitoring-setup
    needs:
      - id: monitoring
        stage: deploy
        targetStage: build

##################################################
## Fourth Level
##################################################

  - type: terraform
    path: '@kateops/@gitlab'
    stateName: kateops/gitlab
    id: gitlab
    needs:
      - id: monitoring-setup
        stage: deploy
        targetStage: build

  - type: terraform
    path: '@kateops/@gitlab-setup'
    stateName: kateops/gitlab-setup
    id: gitlab-setup
    needs:
      - id: gitlab
        stage: deploy
        targetStage: build

  - type: terraform
    path: '@kateops/@administration'
    stateName: kateops/administration
    id: administration
    needs:
      - id: monitoring-setup
        stage: deploy
        targetStage: build

  - type: terraform
    path: '@kateops/@service'
    stateName: kateops/service
    id: service
    needs:
      - id: monitoring-setup
        stage: deploy
        targetStage: build



##################################################
## Terraform Modules
##################################################
#
#  - type: terraform-module
#    path: module/cluster/ingress-nginx
#    moduleName: helm-ingress-nginx
#
#  - type: terraform-module
#    path: module/cluster/openproxy
#    moduleName: helm-openproxy
#
#  - type: terraform-module
#    path: module/terraform/default-rds
#    moduleName: default-rds