apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-psql-cluster
  namespace: ${namespace}
spec:
  affinity:
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      import:
        databases:
          - app
        schemaOnly: false
        source:
          externalCluster: cluster-pg96
        type: microservice
      localeCType: C
      localeCollate: C
      owner: app
  enableSuperuserAccess: true
  externalClusters:
    - connectionParameters:
        dbname: app
        host: gitlab-cnpg-cluster-ro
        port: '5432'
        user: app
      name: cluster-pg96
      password:
        key: password
        name: gitlab-cnpg-cluster-app
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 3
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: 'on'
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: '0'
      log_rotation_size: '0'
      log_truncate_on_rotation: 'false'
      logging_collector: 'on'
      max_connections: '300'
      max_parallel_workers: '32'
      max_replication_slots: '32'
      max_worker_processes: '32'
      shared_memory_type: mmap
      shared_preload_libraries: ''
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _ha_
    updateInterval: 30
  resources: {}
  startDelay: 30
  stopDelay: 30
  storage:
    resizeInUseVolumes: true
    storageClass: gp3
    size: 10Gi
  walStorage:
    resizeInUseVolumes: true
    storageClass: gp3
    size: 5Gi
  switchoverDelay: 40000000
