apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: ${namespace}
  labels:
    logging: grafana-agent
spec:
  image: grafana/agent:v0.28.0
  logLevel: info
  serviceAccountName: prometheus-kube-prometheus-prometheus
  metrics:
    instanceSelector:
      matchLabels:
        logging: grafana-agent
