apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: primary
  namespace: ${namespace}
  labels:
    logging: grafana-agent
spec:
  remoteWrite:
    - url: ${mimir_service}
      headers:
        X-Scope-OrgID: kateops


  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the MetricsInstance CR
  serviceMonitorNamespaceSelector: { }
  serviceMonitorSelector:
    matchLabels:
      logging: grafana-agent

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the MetricsInstance CR.
  podMonitorNamespaceSelector: { }
  podMonitorSelector:
    matchLabels: {}

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the MetricsInstance CR.
  probeNamespaceSelector: { }
  probeSelector:
    matchLabels: {}