{
 "title": "Cluster Overall",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Stats Usage vs Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Real Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (sum((rate(container_cpu_usage_seconds_total{pod!=\"\"}[2m])) * on (node) group_left() (((group by (node)(kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / (sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Real Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (sum((container_memory_working_set_bytes{container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))/ (sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Combined Real Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum((rate(container_cpu_usage_seconds_total{pod!=\"\"}[2m])) * on (node) group_left() (((group by (node)(kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / (sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) + (sum((container_memory_working_set_bytes{container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))/ (sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Real Usage ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " (sum((rate(container_cpu_usage_seconds_total{pod!=\"\"}[2m])) * on (node) group_left() (((group by (node)(kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / (sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Real Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " (sum((container_memory_working_set_bytes{container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))/ (sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Combined Real Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum((rate(container_cpu_usage_seconds_total{pod!=\"\"}[2m])) * on (node) group_left() (((group by (node)(kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / (sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) + (sum((container_memory_working_set_bytes{container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))/ (sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))))) / 2",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "Stats Requests vs Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Resource Allocation ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_cpu_cores{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Resource Allocation ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_memory_bytes{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Combined Resource Allocation ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_cpu_cores{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))) + (sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_memory_bytes{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Resource Allocation ",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_cpu_cores{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Resource Allocation ",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_memory_bytes{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Complete Resource Allocation ",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_cpu_cores{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))) + (sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_memory_bytes{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))) / 2",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Complete Resource Waste",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_cpu_cores{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))",
     "legendFormat": "Memory"
    },
    {
     "expr": "1 - ((sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_memory_bytes{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Resource Allocation ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_cpu_cores{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Resource Allocation ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_memory_bytes{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Complete Resource Allocation ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum((kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_cpu_cores{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))) + (sum((kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\", container!=\"\"}) * on (node) group_left() (((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"})))))) / sum((kube_node_status_allocatable_memory_bytes{}) * on (node) group_left() ((group by (node) (kube_node_labels{label_karpenter_sh_provisioner_name=\"default-spot\"}))))) / 2",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum((rate(container_cpu_usage_seconds_total{pod!=\"\"}[2m])))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(sum by (node) (kube_node_status_capacity_cpu_cores{pod!~\"ksm.*\"}))",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(sum by (pod) (kube_pod_container_resource_requests{resource=\"cpu\", pod!~\"ksm.*\", container!=\"\"}))",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Cluster Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(sum by (container) (container_memory_working_set_bytes{name!=\"\"}))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\", pod!~\"ksm.*\",  pod!=\"\"}))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(sum by (node) (kube_node_status_allocatable_memory_bytes{ pod!~\"ksm.*\", node!=\"\"}))",
       "legendFormat": "Available"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_container_resource_requests{ pod!~\"ksm.*\", resource=\"cpu\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{name!=\"\",  pod!~\"ksm.*\", namespace!=\"\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_container_resource_requests{ pod!~\"ksm.*\", resource=\"memory\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (namespace) (container_memory_working_set_bytes{name!=\"\", namespace!=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}