{
 "title": "K8-Cluster",
 "tags": [
  "Kubernetes",
  "DNS"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pvc",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes, persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Api Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": " sum by (group) (rate(apiserver_request_total{}[$__rate_interval]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "DNS Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(coredns_dns_requests_total{container=\"coredns\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Service RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container) (max_over_time(container_memory_max_usage_bytes{container!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Service CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]) * 100)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Storage - PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "$pvc",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
   "repeat": "pvc",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)\r\n  /\r\nsum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage - $pvc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }, "repeat": "pvc" },
  {
   "title": "$pvc",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)\r\n  /\r\nsum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)\r\n - sum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)\r\n",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(max_over_time(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}[$__interval])) by (persistentvolumeclaim)\n - sum(min_over_time(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$pvc\"}[$__interval])) by (persistentvolumeclaim)\n",
     "legendFormat": "Max Used"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)\r\n",
     "legendFormat": "Capacity"
    }
   ]
  }
 ]
}