{
 "title": "K8-Cluster Mimir",
 "tags": [
  "Mimir",
  "Cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_cpu_allocation, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container) (max_over_time(container_memory_working_set_bytes{container!=\"\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Service RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (container) (max_over_time(container_memory_working_set_bytes{container!=\"\",namespace=\"$namespace\"}[$__rate_interval]))) / (sum by (container) (max_over_time(container_memory_allocation_bytes{container!=\"\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Service CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\"}[5m])) by (container)    ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service CPU used/allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\n       sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])) by (container) \n      / (sum by (container) (container_cpu_allocation{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}