{
 "title": "Pod Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_allocation, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_allocation{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum by (container) (max_over_time(container_memory_working_set_bytes{container!=\"\", pod=\"$pod\",namespace=\"$namespace\"}[$__rate_interval])))/ (sum by (container) (max_over_time(container_memory_allocation_bytes{container!=\"\", pod=\"$pod\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum by (container) (rate(container_cpu_usage_seconds_total{pod=\"$pod\",namespace=\"$namespace\", container!=\"\"}[2m]))) / (sum by (container) (container_cpu_allocation{pod=\"$pod\",namespace=\"$namespace\", container!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Usage by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container) (max_over_time(container_memory_working_set_bytes{container!=\"\", pod=\"$pod\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "usage-{{container}}"
    },
    {
     "expr": "(max_over_time(container_memory_allocation_bytes{container!=\"\", pod=\"$pod\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "requests-{{container}}"
    },
    {
     "expr": "sum by (container) (kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container!=\"\"})",
     "legendFormat": "limits-{{container}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Usage by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=\"$pod\",namespace=\"$namespace\", container!=\"\"}[2m])",
     "legendFormat": "usage-{{container}}"
    },
    {
     "expr": "container_cpu_allocation{pod=\"$pod\",namespace=\"$namespace\", container!=\"\"}",
     "legendFormat": "requests-{{container}}"
    },
    {
     "expr": "sum by (container) (kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\",namespace=\"$namespace\", container!=\"\"})",
     "legendFormat": "limits-{{container}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pod Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=\"$pod\", namespace=\"$namespace\"}[2m])",
     "legendFormat": "Received"
    },
    {
     "expr": "- rate(container_network_transmit_bytes_total{pod=\"$pod\", namespace=\"$namespace\"}[2m])",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}