apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-spot
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand", "spot"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
%{ for az in availability_zones ~}
        - ${az}
%{ endfor ~}
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Gt
      values: ["2"]
    - key: "beta.kubernetes.io/os"
      operator: In
      values: ["linux"]
    - key: "beta.kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Lt
      values: ["16"]
    - key: "karpenter.k8s.aws/instance-hypervisor"
      operator: In
      values: ["nitro"]
  limits:
    resources:
      cpu: 40
  providerRef:
    name: default-spot
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 86400 # 10800 3 hours | 21600 6 hours | 86400 24 hours
  weight: 100
  kubeletConfiguration:
    evictionMaxPodGracePeriod: 180