apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-spot
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
%{ for az in availability_zones ~}
        - ${az}
%{ endfor ~}
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Gt
      values: ["2"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Lt
      values: ["12"]

  limits:
    resources:
      cpu: 20
  providerRef:
    name: default-spot
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 2592000
  weight: 100
