apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-stable
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
%{ for az in availability_zones ~}
        - ${az}
%{ endfor ~}
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Gt
      values: ["3"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Lt
      values: ["12"]
  limits:
    resources:
      cpu: 20
  providerRef:
    name: default-stable
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 2592000
  weight: 100


  taints:
    - key: provisioner/stable
      value: "true"
      effect: NoSchedule