apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${application_name}
  namespace: ${namespace}
spec:
  project: ${namespace}
  source:
    repoURL: ${repo_url}
    targetRevision: HEAD
    path: .argo
    helm:
      releaseName: atlas-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${namespace}