apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${application_name}
  namespace: argo
spec:
  project: ${namespace}
  source:
    repoURL: ${repo_url}
    targetRevision: ${default_branch}
    path: ${application_name}
    directory:
      recurse: true
      include: '*'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${namespace}