apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${namespace}-${application_name}
  namespace: argo
spec:
  project: ${namespace}
  source:
    repoURL: ${repo_url}
    targetRevision: ${default_branch}
    path: ${application_name}
    directory:
      recurse: true
      include: '*'
      exclude: '*.dev.yaml'
  destination:
    name: in-cluster
    namespace: ${namespace}
