apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${name}
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:

  triggers:
    - type: cron
      metadata:
        timezone: Europe/Berlin
        start: 0 7 * * *
        end: 0 1 * * *
        desiredReplicas: "1"
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        metricName: container_memory_max_usage_bytes
        threshold: '0.5'
        activationThreshold: '0.4'
        query: (sum by (container) (container_memory_usage_bytes{container="${container_name}"})) / (sum by (container) (container_memory_allocation_bytes{container="${container_name}"}))

#    - type: memory
#      metricType: Utilization
#      metadata:
#        value: "80"
