apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${name}
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: false
  triggers:
    - type: cron
      metadata:
        timezone: Europe/Berlin
        start: 0 8 * * *
        end: 0 0 * * *
        desiredReplicas: "2"
    - type: cron
      metadata:
        timezone: Europe/Berlin
        start: 0 0 * * *
        end: 0 11 * * *
        desiredReplicas: "1"
    - type: prometheus
      metadata:
        serverAddress: http://mimir-gateway.monitoring.svc.cluster.local:80
        metricName: container_memory_max_usage_bytes
        threshold: '0.8'
        activationThreshold: '0.6'
        query: (sum by (container) (container_memory_working_set_bytes{container="${container_name}"})) / (sum by (container) (container_memory_allocation_bytes{container="${container_name}"}))

#    - type: memory
#      metricType: Utilization
#      metadata:
#        value: "80"
