{
 "title": "Logs",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "HTTP code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2XX",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\nsum by (http_status) (count_over_time(\n{app=\"ingress-nginx\"}[24h] | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]` |http_status=~\"^[0-9]*$\" |http_status >= 200 | http_status < 300))\n)"
    }
   ]
  },
  {
   "title": "Bad",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nsum by (http_status) (count_over_time(\n{app=\"ingress-nginx\"}[24h] | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]` |http_status=~\"^[0-9]*$\" |http_status >= 500 | http_status < 600))\n)",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(\nsum by (http_status) (count_over_time(\n{app=\"ingress-nginx\"}[24h] | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]` |http_status=~\"^[0-9]*$\" |http_status >= 400 | http_status < 500))\n)",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(\nsum by (http_status) (count_over_time(\n{app=\"ingress-nginx\"}[24h] | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]` |http_status=~\"^[0-9]*$\" |http_status >= 300 | http_status < 400))\n)",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(\nsum by (http_status) (count_over_time(\n{app=\"ingress-nginx\"}[24h] | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]` |http_status=~\"^[0-9]*$\" |http_status >= 100 | http_status < 200))\n)",
     "legendFormat": "1XX"
    }
   ]
  },
  {
   "title": "Status per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "\nsum by (http_status) (count_over_time(\n{app=\"ingress-nginx\"}[1m] | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]` |http_status=~\"^[0-9]*$\" |http_status >= 100 | http_status < 600))\n",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{app=\"ingress-nginx\"} | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]`"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Services",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\nsum by (service) (count_over_time(\n{app=\"ingress-nginx\"}[24h] | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]` |http_status=~\"^[0-9]*$\" |http_status >= 100 | http_status < 600 |service!=\"\"))\n",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\nsum by (service) (count_over_time(\n{app=\"ingress-nginx\"}[24h] | pattern `<_> [<time>] \"<method> <request_uri> <http_version>\" <http_status> <_> \"<_>\" \"<agent>\" <_> [<service>]` |http_status=~\"^[0-9]*$\" |http_status >= 300 or http_status < 200 |service!=\"\"))\n",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  }
 ]
}