kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ${name}
  namespace: argo
spec:
  permitOnlyProjectScopedClusters: false
  destinations:
    - namespace: ${namespace}
      server: https://kubernetes.default.svc
      name: in-cluster
  sourceNamespaces:
    - ${namespace}
  sourceRepos:
    - '${gitlab_project_url}/argo'
