kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ${namespace}
  namespace: argo
spec:
  destinations:
    - namespace: ${namespace}
      server: https://kubernetes.default.svc
      name: in-cluster

  sourceRepos:
    - '${gitlab_project_url}/*'

  sourceNamespaces:
    - ${namespace}