apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: runner-buildkit
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - "eu-central-1a"
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Gt
      values: ["3"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Lt
      values: ["9"]
    - key: "karpenter.k8s.aws/instance-memory"
      operator: Gt
      values: ["10000"]

  labels:
%{ for key,value in labels }
    ${key}: ${value}
%{ endfor }
  taints:
%{ for key,value in labels }
    - key: ${key}
      effect: NoExecute
      value: "${value}"
%{ endfor }

  limits:
    resources:
      cpu: 40
  providerRef:
    name: default-spot
  ttlSecondsAfterEmpty: 6
  ttlSecondsUntilExpired: 6000
  weight: 100
