apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ${kind}
    name: ${name}
  pollingInterval: 3
  cooldownPeriod: 30
  idleReplicaCount: 1
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: false
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://mimir-query-frontend.monitoring.svc.cluster.local:8080/prometheus
        query: sum(rate(container_cpu_usage_seconds_total{pod=~"buildkitd-.*", cpu="total"}[2m])) / sum(container_cpu_allocation{pod=~"buildkitd-.*"})
        threshold: '2'
        customHeaders: X-Scope-OrgID=kateops
